spring.application.name=authentication-server,config-server,domain
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.label=${RAILWAY_ENVIRONMENT_NAME:develop}
spring.profiles.active=${GIT_PROFILE:containerdev}
spring.cloud.compatibility-verifier.enabled=false

# Server Configuration
server.port=${AUTHENTICATION_SERVER_PORT:8090}

# Management Configuration
management.server.ssl.enabled=false
management.endpoint.health.access=read_only
management.health.diskspace.enabled=false
management.endpoints.web.exposure.include=health,loggers,info,decrypt
management.endpoints.web.path-mapping.loggers=loggers
management.endpoints.web.path-mapping.health=health
management.endpoints.web.path-mapping.info=info
management.endpoints.web.path-mapping.decrypt=decrypt

management.endpoint.health.probes.add-additional-paths=true
management.server.port=${server.port}
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:j0g42025}

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.registry-fetch-interval-seconds=10
eureka.client.initial-instance-info-replication-interval-seconds=10